### ISSUE TITLE
Requested format is not available

### ISSUE THREAD

**Issue by MoonShined111** [glomatico/gytmdl#35]
Tried updating Gytmdl and Yt-dlp to newest version, trying different formats, putting cookies (I have Yt music premium) but still it complaing "requested format not available". Last summer this worked like a charm, when I last time used it.

gytmdl "https://music.youtube.com/watch?v=uzlU9bZ-5NQ&si=dJE6QE_LmUseasaP"
[INFO     19:18:06] Starting Gytmdl
[INFO     19:18:06] (URL 1/1) Checking "https://music.youtube.com/watch?v=uzlU9bZ-5NQ&si=dJE6QE_LmUseasaP"
ERROR: [youtube] uzlU9bZ-5NQ: Requested format is not available. Use --list-formats for a list of available formats
[ERROR    19:18:09] (URL 1/1) Failed to check "https://music.youtube.com/watch?v=uzlU9bZ-5NQ&si=dJE6QE_LmUseasaP"
Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1637, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1793, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1852, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2986, in process_video_result
    raise ExtractorError(
        'Requested format is not available. Use --list-formats for a list of available formats',
        expected=True, video_id=info_dict['id'], ie=info_dict['extractor'])
yt_dlp.utils.ExtractorError: [youtube] uzlU9bZ-5NQ: Requested format is not available. Use --list-formats for a list of available formats

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python313\Lib\site-packages\gytmdl\cli.py", line 290, in main
    download_queue = list(downloader.get_download_queue(url))
  File "C:\Program Files\Python313\Lib\site-packages\gytmdl\downloader.py", line 113, in get_download_queue
    yield from self._get_download_queue_url(url)
  File "C:\Program Files\Python313\Lib\site-packages\gytmdl\downloader.py", line 119, in _get_download_queue_url
    ytdlp_info = self._get_ytdlp_info(url.split("&")[0])
  File "C:\Program Files\Python313\Lib\site-packages\gytmdl\downloader.py", line 103, in _get_ytdlp_info
    return ydl.extract_info(url, download=False)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1626, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1655, in wrapper
    self.report_error(str(e), e.format_traceback())
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1095, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1034, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] uzlU9bZ-5NQ: Requested format is not available. Use --list-formats for a list of available formats
[INFO     19:18:09] Done (1 error(s))

**Comment by glomatico** [comment]
Fixed on the latest release.

**Comment by RaphCayou** [comment]
@glomatico Hello I am still getting this error when requesting the 141 format with fresh cookies.txt and fully updated dependencies. Would you know how to guide me through this? Thanks!
